version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/" # Location of package manifest
    schedule:
      interval: "daily"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
