version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/" # Location of package manifest
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
