[package]
name = "room_private"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
tokio-tungstenite = "0.21"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes-gcm = "0.10"
rand = "0.8"
sha2 = "0.10"
base64 = "0.21"
<<<<<<< HEAD
warp = { version = "0.3", features = ["tls"] }
=======
warp = "0.3"
>>>>>>> 00c1f4839a252783e3cac59c97d2ddf1744fdb95
uuid = { version = "1.6", features = ["v4"] }
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"
async-trait = "0.1"
<<<<<<< HEAD
rustls = "0.21"
rustls-pemfile = "1.0"
=======
>>>>>>> 00c1f4839a252783e3cac59c97d2ddf1744fdb95
