name: mirror-repository

on:
  push:
  

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror repository to Codeberg #I may be stupid
        uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'https://codeberg.org/urwq/RoomPrivate'
          GIT_USERNAME: c0dezin
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          GIT_REF: refs/heads/main
